### ISSUE TITLE
How to predict upcoming matches

### ISSUE THREAD

**Issue by pmxpo** [opisthokonta/goalmodel#1]
Thank you very much for this working code. However, I would like to ask for clarification.
The data loaded in this code is for EPL 2011, 

1.) How do we change the data from 2011 to 2018 (I tried but got an error (Error in goalmodel(goals1 = england_2011$hgoal, goals2 = england_2011$vgoal,  : 
  length(goals1) >= 1 is not TRUE)

2.) How do we change the league

3.) Is it possible to call this code from the GUI so that, it becomes easy to use the code for many other predictions?

Your response would be highly appreciated as I am a newbie here and willing to learn.

Thank you

**Comment by opisthokonta** [comment]
The data used in the examples are from the engsoccerdata package. This package only contains historical data, and is not updated that often. It does contain data from other leagues, however. For more up to date data check out http://www.football-data.co.uk/data.php. 

I have no plans for making a GUI.

**Comment by opisthokonta** [comment]
No, not with my code. There are several built-in functions in R to read in data files. Check out the read.csv() function, it should do the job.

**Comment by pmxpo** [comment]
Can you assist me with any function that can do basic predictions please. I am unable to do my own code.

**Comment by opisthokonta** [comment]
I have provided a lot of examples in the readme you see on the front page. I suggest you consult some general R tutorials to learn how to use R.

**Comment by pmxpo** [comment]
Thanks
